version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - GIN_MODE=debug
      - POSTGRES_DSN=postgres://postgres:password@localhost:5433/tasks
      - SERVER_ADDRESS=localhost:8388
      - LOGIN_SYMMETRIC_KEY=892WHFGU874239823WJE229

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tasks
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
